// Generates apps/web/lib/catalog-data.ts with the lists of design systems
// and skills found under <repo>/design-systems/ and <repo>/skills/. The
// generated file is imported by /api/design-systems and /api/skills routes
// so Vercel's Node File Tracing bundles the data with the function (the
// raw directories aren't traced into /var/task at runtime).
import { existsSync, readFileSync, readdirSync, statSync, writeFileSync, mkdirSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const REPO_ROOT = join(__dirname, "..", "..", "..");
const OUT_DIR = join(__dirname, "..", "lib");
const OUT_FILE = join(OUT_DIR, "catalog-data.ts");

function readMeta(dir, files) {
  for (const f of files) {
    const p = join(dir, f);
    if (existsSync(p)) {
      try {
        const raw = readFileSync(p, "utf8");
        if (f.endsWith(".json")) return JSON.parse(raw);
        return { _raw: raw };
      } catch {
        return null;
      }
    }
  }
  return null;
}

function listDir(name) {
  const full = join(REPO_ROOT, name);
  if (!existsSync(full)) return [];
  const out = [];
  for (const entry of readdirSync(full)) {
    const p = join(full, entry);
    try {
      if (!statSync(p).isDirectory()) continue;
    } catch {
      continue;
    }
    const meta = readMeta(p, ["design-system.json", "skill.json", "manifest.json"]);
    const description = typeof meta?.description === "string" ? meta.description : undefined;
    const displayName = typeof meta?.name === "string" ? meta.name : entry;
    out.push({ id: entry, slug: entry, name: displayName, description });
  }
  out.sort((a, b) => a.slug.localeCompare(b.slug));
  return out;
}

const designSystems = listDir("design-systems");
const skills = listDir("skills");

const out = `// Auto-generated by apps/web/scripts/generate-catalog.mjs at build time.
// Do not edit by hand. Regenerated on every \`next build\`.
export interface CatalogEntry {
  id: string;
  slug: string;
  name: string;
  description?: string;
}

export const designSystems: CatalogEntry[] = ${JSON.stringify(designSystems, null, 2)};

export const skills: CatalogEntry[] = ${JSON.stringify(skills, null, 2)};
`;

mkdirSync(OUT_DIR, { recursive: true });
writeFileSync(OUT_FILE, out);
console.log(`[generate-catalog] wrote ${OUT_FILE}: ${designSystems.length} design systems, ${skills.length} skills`);
