/* eslint-disable */
/**
 * Generated `api` reference for Convex functions.
 *
 * Auto-generated by `npx convex dev`. This file is normally regenerated on every
 * `convex dev` run. Until a CONVEX_DEPLOY_KEY is configured, this hand-written
 * stub mirrors the module exports under `convex/*.ts` so that web app code can
 * `import { api } from "convex/_generated/api"` without TypeScript errors.
 *
 * After running real codegen this file will be overwritten — that's expected.
 */
import type { ApiFromModules, FilterApi, FunctionReference } from "convex/server";
import type * as users from "../users.js";
import type * as projects from "../projects.js";
import type * as conversations from "../conversations.js";
import type * as messages from "../messages.js";
import type * as templates from "../templates.js";
import type * as providerCredentials from "../providerCredentials.js";
import type * as appConfig from "../appConfig.js";
import type * as catalog from "../catalog.js";

declare const fullApi: ApiFromModules<{
  users: typeof users;
  projects: typeof projects;
  conversations: typeof conversations;
  messages: typeof messages;
  templates: typeof templates;
  providerCredentials: typeof providerCredentials;
  appConfig: typeof appConfig;
  catalog: typeof catalog;
}>;

export declare const api: FilterApi<typeof fullApi, FunctionReference<any, "public">>;
export declare const internal: FilterApi<typeof fullApi, FunctionReference<any, "internal">>;
