/* eslint-disable */
/**
 * Generated `api` reference for Convex functions.
 * Auto-generated by `npx convex dev`. This stub is replaced on first codegen.
 */
import type { ApiFromModules, FilterApi, FunctionReference } from "convex/server";
import type * as users from "../users.js";

declare const fullApi: ApiFromModules<{
  users: typeof users;
}>;

export declare const api: FilterApi<typeof fullApi, FunctionReference<any, "public">>;
export declare const internal: FilterApi<typeof fullApi, FunctionReference<any, "internal">>;
