// Auto-generated by apps/web/scripts/generate-catalog.mjs at build time.
// Do not edit by hand. Regenerated on every `next build`.
export interface CatalogEntry {
  id: string;
  slug: string;
  name: string;
  description?: string;
}

export const designSystems: CatalogEntry[] = [
  {
    "id": "agentic",
    "slug": "agentic",
    "name": "agentic"
  },
  {
    "id": "airbnb",
    "slug": "airbnb",
    "name": "airbnb"
  },
  {
    "id": "airtable",
    "slug": "airtable",
    "name": "airtable"
  },
  {
    "id": "ant",
    "slug": "ant",
    "name": "ant"
  },
  {
    "id": "apple",
    "slug": "apple",
    "name": "apple"
  },
  {
    "id": "application",
    "slug": "application",
    "name": "application"
  },
  {
    "id": "arc",
    "slug": "arc",
    "name": "arc"
  },
  {
    "id": "artistic",
    "slug": "artistic",
    "name": "artistic"
  },
  {
    "id": "atelier-zero",
    "slug": "atelier-zero",
    "name": "atelier-zero"
  },
  {
    "id": "bento",
    "slug": "bento",
    "name": "bento"
  },
  {
    "id": "binance",
    "slug": "binance",
    "name": "binance"
  },
  {
    "id": "bmw",
    "slug": "bmw",
    "name": "bmw"
  },
  {
    "id": "bold",
    "slug": "bold",
    "name": "bold"
  },
  {
    "id": "brutalism",
    "slug": "brutalism",
    "name": "brutalism"
  },
  {
    "id": "bugatti",
    "slug": "bugatti",
    "name": "bugatti"
  },
  {
    "id": "cafe",
    "slug": "cafe",
    "name": "cafe"
  },
  {
    "id": "cal",
    "slug": "cal",
    "name": "cal"
  },
  {
    "id": "canva",
    "slug": "canva",
    "name": "canva"
  },
  {
    "id": "claude",
    "slug": "claude",
    "name": "claude"
  },
  {
    "id": "clay",
    "slug": "clay",
    "name": "clay"
  },
  {
    "id": "claymorphism",
    "slug": "claymorphism",
    "name": "claymorphism"
  },
  {
    "id": "clean",
    "slug": "clean",
    "name": "clean"
  },
  {
    "id": "clickhouse",
    "slug": "clickhouse",
    "name": "clickhouse"
  },
  {
    "id": "cohere",
    "slug": "cohere",
    "name": "cohere"
  },
  {
    "id": "coinbase",
    "slug": "coinbase",
    "name": "coinbase"
  },
  {
    "id": "colorful",
    "slug": "colorful",
    "name": "colorful"
  },
  {
    "id": "composio",
    "slug": "composio",
    "name": "composio"
  },
  {
    "id": "contemporary",
    "slug": "contemporary",
    "name": "contemporary"
  },
  {
    "id": "corporate",
    "slug": "corporate",
    "name": "corporate"
  },
  {
    "id": "cosmic",
    "slug": "cosmic",
    "name": "cosmic"
  },
  {
    "id": "creative",
    "slug": "creative",
    "name": "creative"
  },
  {
    "id": "cursor",
    "slug": "cursor",
    "name": "cursor"
  },
  {
    "id": "dashboard",
    "slug": "dashboard",
    "name": "dashboard"
  },
  {
    "id": "default",
    "slug": "default",
    "name": "default"
  },
  {
    "id": "discord",
    "slug": "discord",
    "name": "discord"
  },
  {
    "id": "dithered",
    "slug": "dithered",
    "name": "dithered"
  },
  {
    "id": "doodle",
    "slug": "doodle",
    "name": "doodle"
  },
  {
    "id": "dramatic",
    "slug": "dramatic",
    "name": "dramatic"
  },
  {
    "id": "duolingo",
    "slug": "duolingo",
    "name": "duolingo"
  },
  {
    "id": "editorial",
    "slug": "editorial",
    "name": "editorial"
  },
  {
    "id": "elegant",
    "slug": "elegant",
    "name": "elegant"
  },
  {
    "id": "elevenlabs",
    "slug": "elevenlabs",
    "name": "elevenlabs"
  },
  {
    "id": "energetic",
    "slug": "energetic",
    "name": "energetic"
  },
  {
    "id": "enterprise",
    "slug": "enterprise",
    "name": "enterprise"
  },
  {
    "id": "expo",
    "slug": "expo",
    "name": "expo"
  },
  {
    "id": "expressive",
    "slug": "expressive",
    "name": "expressive"
  },
  {
    "id": "fantasy",
    "slug": "fantasy",
    "name": "fantasy"
  },
  {
    "id": "ferrari",
    "slug": "ferrari",
    "name": "ferrari"
  },
  {
    "id": "figma",
    "slug": "figma",
    "name": "figma"
  },
  {
    "id": "flat",
    "slug": "flat",
    "name": "flat"
  },
  {
    "id": "framer",
    "slug": "framer",
    "name": "framer"
  },
  {
    "id": "friendly",
    "slug": "friendly",
    "name": "friendly"
  },
  {
    "id": "futuristic",
    "slug": "futuristic",
    "name": "futuristic"
  },
  {
    "id": "github",
    "slug": "github",
    "name": "github"
  },
  {
    "id": "glassmorphism",
    "slug": "glassmorphism",
    "name": "glassmorphism"
  },
  {
    "id": "gradient",
    "slug": "gradient",
    "name": "gradient"
  },
  {
    "id": "hashicorp",
    "slug": "hashicorp",
    "name": "hashicorp"
  },
  {
    "id": "huggingface",
    "slug": "huggingface",
    "name": "huggingface"
  },
  {
    "id": "ibm",
    "slug": "ibm",
    "name": "ibm"
  },
  {
    "id": "intercom",
    "slug": "intercom",
    "name": "intercom"
  },
  {
    "id": "kami",
    "slug": "kami",
    "name": "kami"
  },
  {
    "id": "kraken",
    "slug": "kraken",
    "name": "kraken"
  },
  {
    "id": "lamborghini",
    "slug": "lamborghini",
    "name": "lamborghini"
  },
  {
    "id": "levels",
    "slug": "levels",
    "name": "levels"
  },
  {
    "id": "linear-app",
    "slug": "linear-app",
    "name": "linear-app"
  },
  {
    "id": "lingo",
    "slug": "lingo",
    "name": "lingo"
  },
  {
    "id": "lovable",
    "slug": "lovable",
    "name": "lovable"
  },
  {
    "id": "luxury",
    "slug": "luxury",
    "name": "luxury"
  },
  {
    "id": "mastercard",
    "slug": "mastercard",
    "name": "mastercard"
  },
  {
    "id": "material",
    "slug": "material",
    "name": "material"
  },
  {
    "id": "meta",
    "slug": "meta",
    "name": "meta"
  },
  {
    "id": "minimal",
    "slug": "minimal",
    "name": "minimal"
  },
  {
    "id": "minimax",
    "slug": "minimax",
    "name": "minimax"
  },
  {
    "id": "mintlify",
    "slug": "mintlify",
    "name": "mintlify"
  },
  {
    "id": "miro",
    "slug": "miro",
    "name": "miro"
  },
  {
    "id": "mistral-ai",
    "slug": "mistral-ai",
    "name": "mistral-ai"
  },
  {
    "id": "modern",
    "slug": "modern",
    "name": "modern"
  },
  {
    "id": "mongodb",
    "slug": "mongodb",
    "name": "mongodb"
  },
  {
    "id": "mono",
    "slug": "mono",
    "name": "mono"
  },
  {
    "id": "neobrutalism",
    "slug": "neobrutalism",
    "name": "neobrutalism"
  },
  {
    "id": "neon",
    "slug": "neon",
    "name": "neon"
  },
  {
    "id": "neumorphism",
    "slug": "neumorphism",
    "name": "neumorphism"
  },
  {
    "id": "nike",
    "slug": "nike",
    "name": "nike"
  },
  {
    "id": "notion",
    "slug": "notion",
    "name": "notion"
  },
  {
    "id": "nvidia",
    "slug": "nvidia",
    "name": "nvidia"
  },
  {
    "id": "ollama",
    "slug": "ollama",
    "name": "ollama"
  },
  {
    "id": "openai",
    "slug": "openai",
    "name": "openai"
  },
  {
    "id": "opencode-ai",
    "slug": "opencode-ai",
    "name": "opencode-ai"
  },
  {
    "id": "pacman",
    "slug": "pacman",
    "name": "pacman"
  },
  {
    "id": "paper",
    "slug": "paper",
    "name": "paper"
  },
  {
    "id": "perspective",
    "slug": "perspective",
    "name": "perspective"
  },
  {
    "id": "pinterest",
    "slug": "pinterest",
    "name": "pinterest"
  },
  {
    "id": "playstation",
    "slug": "playstation",
    "name": "playstation"
  },
  {
    "id": "posthog",
    "slug": "posthog",
    "name": "posthog"
  },
  {
    "id": "premium",
    "slug": "premium",
    "name": "premium"
  },
  {
    "id": "professional",
    "slug": "professional",
    "name": "professional"
  },
  {
    "id": "publication",
    "slug": "publication",
    "name": "publication"
  },
  {
    "id": "raycast",
    "slug": "raycast",
    "name": "raycast"
  },
  {
    "id": "refined",
    "slug": "refined",
    "name": "refined"
  },
  {
    "id": "renault",
    "slug": "renault",
    "name": "renault"
  },
  {
    "id": "replicate",
    "slug": "replicate",
    "name": "replicate"
  },
  {
    "id": "resend",
    "slug": "resend",
    "name": "resend"
  },
  {
    "id": "retro",
    "slug": "retro",
    "name": "retro"
  },
  {
    "id": "revolut",
    "slug": "revolut",
    "name": "revolut"
  },
  {
    "id": "runwayml",
    "slug": "runwayml",
    "name": "runwayml"
  },
  {
    "id": "sanity",
    "slug": "sanity",
    "name": "sanity"
  },
  {
    "id": "sentry",
    "slug": "sentry",
    "name": "sentry"
  },
  {
    "id": "shadcn",
    "slug": "shadcn",
    "name": "shadcn"
  },
  {
    "id": "shopify",
    "slug": "shopify",
    "name": "shopify"
  },
  {
    "id": "simple",
    "slug": "simple",
    "name": "simple"
  },
  {
    "id": "skeumorphism",
    "slug": "skeumorphism",
    "name": "skeumorphism"
  },
  {
    "id": "sleek",
    "slug": "sleek",
    "name": "sleek"
  },
  {
    "id": "spacex",
    "slug": "spacex",
    "name": "spacex"
  },
  {
    "id": "spacious",
    "slug": "spacious",
    "name": "spacious"
  },
  {
    "id": "spotify",
    "slug": "spotify",
    "name": "spotify"
  },
  {
    "id": "starbucks",
    "slug": "starbucks",
    "name": "starbucks"
  },
  {
    "id": "storytelling",
    "slug": "storytelling",
    "name": "storytelling"
  },
  {
    "id": "stripe",
    "slug": "stripe",
    "name": "stripe"
  },
  {
    "id": "supabase",
    "slug": "supabase",
    "name": "supabase"
  },
  {
    "id": "superhuman",
    "slug": "superhuman",
    "name": "superhuman"
  },
  {
    "id": "tesla",
    "slug": "tesla",
    "name": "tesla"
  },
  {
    "id": "tetris",
    "slug": "tetris",
    "name": "tetris"
  },
  {
    "id": "theverge",
    "slug": "theverge",
    "name": "theverge"
  },
  {
    "id": "together-ai",
    "slug": "together-ai",
    "name": "together-ai"
  },
  {
    "id": "totality-festival",
    "slug": "totality-festival",
    "name": "totality-festival"
  },
  {
    "id": "uber",
    "slug": "uber",
    "name": "uber"
  },
  {
    "id": "vercel",
    "slug": "vercel",
    "name": "vercel"
  },
  {
    "id": "vibrant",
    "slug": "vibrant",
    "name": "vibrant"
  },
  {
    "id": "vintage",
    "slug": "vintage",
    "name": "vintage"
  },
  {
    "id": "vodafone",
    "slug": "vodafone",
    "name": "vodafone"
  },
  {
    "id": "voltagent",
    "slug": "voltagent",
    "name": "voltagent"
  },
  {
    "id": "warm-editorial",
    "slug": "warm-editorial",
    "name": "warm-editorial"
  },
  {
    "id": "warp",
    "slug": "warp",
    "name": "warp"
  },
  {
    "id": "webflow",
    "slug": "webflow",
    "name": "webflow"
  },
  {
    "id": "wired",
    "slug": "wired",
    "name": "wired"
  },
  {
    "id": "wise",
    "slug": "wise",
    "name": "wise"
  },
  {
    "id": "x-ai",
    "slug": "x-ai",
    "name": "x-ai"
  },
  {
    "id": "xiaohongshu",
    "slug": "xiaohongshu",
    "name": "xiaohongshu"
  },
  {
    "id": "zapier",
    "slug": "zapier",
    "name": "zapier"
  }
];

export const skills: CatalogEntry[] = [
  {
    "id": "audio-jingle",
    "slug": "audio-jingle",
    "name": "audio-jingle"
  },
  {
    "id": "blog-post",
    "slug": "blog-post",
    "name": "blog-post"
  },
  {
    "id": "critique",
    "slug": "critique",
    "name": "critique"
  },
  {
    "id": "dashboard",
    "slug": "dashboard",
    "name": "dashboard"
  },
  {
    "id": "dating-web",
    "slug": "dating-web",
    "name": "dating-web"
  },
  {
    "id": "design-brief",
    "slug": "design-brief",
    "name": "design-brief"
  },
  {
    "id": "digital-eguide",
    "slug": "digital-eguide",
    "name": "digital-eguide"
  },
  {
    "id": "docs-page",
    "slug": "docs-page",
    "name": "docs-page"
  },
  {
    "id": "email-marketing",
    "slug": "email-marketing",
    "name": "email-marketing"
  },
  {
    "id": "eng-runbook",
    "slug": "eng-runbook",
    "name": "eng-runbook"
  },
  {
    "id": "finance-report",
    "slug": "finance-report",
    "name": "finance-report"
  },
  {
    "id": "gamified-app",
    "slug": "gamified-app",
    "name": "gamified-app"
  },
  {
    "id": "guizang-ppt",
    "slug": "guizang-ppt",
    "name": "guizang-ppt"
  },
  {
    "id": "hatch-pet",
    "slug": "hatch-pet",
    "name": "hatch-pet"
  },
  {
    "id": "hr-onboarding",
    "slug": "hr-onboarding",
    "name": "hr-onboarding"
  },
  {
    "id": "html-ppt",
    "slug": "html-ppt",
    "name": "html-ppt"
  },
  {
    "id": "html-ppt-course-module",
    "slug": "html-ppt-course-module",
    "name": "html-ppt-course-module"
  },
  {
    "id": "html-ppt-dir-key-nav-minimal",
    "slug": "html-ppt-dir-key-nav-minimal",
    "name": "html-ppt-dir-key-nav-minimal"
  },
  {
    "id": "html-ppt-graphify-dark-graph",
    "slug": "html-ppt-graphify-dark-graph",
    "name": "html-ppt-graphify-dark-graph"
  },
  {
    "id": "html-ppt-hermes-cyber-terminal",
    "slug": "html-ppt-hermes-cyber-terminal",
    "name": "html-ppt-hermes-cyber-terminal"
  },
  {
    "id": "html-ppt-knowledge-arch-blueprint",
    "slug": "html-ppt-knowledge-arch-blueprint",
    "name": "html-ppt-knowledge-arch-blueprint"
  },
  {
    "id": "html-ppt-obsidian-claude-gradient",
    "slug": "html-ppt-obsidian-claude-gradient",
    "name": "html-ppt-obsidian-claude-gradient"
  },
  {
    "id": "html-ppt-pitch-deck",
    "slug": "html-ppt-pitch-deck",
    "name": "html-ppt-pitch-deck"
  },
  {
    "id": "html-ppt-presenter-mode-reveal",
    "slug": "html-ppt-presenter-mode-reveal",
    "name": "html-ppt-presenter-mode-reveal"
  },
  {
    "id": "html-ppt-product-launch",
    "slug": "html-ppt-product-launch",
    "name": "html-ppt-product-launch"
  },
  {
    "id": "html-ppt-taste-brutalist",
    "slug": "html-ppt-taste-brutalist",
    "name": "html-ppt-taste-brutalist"
  },
  {
    "id": "html-ppt-taste-editorial",
    "slug": "html-ppt-taste-editorial",
    "name": "html-ppt-taste-editorial"
  },
  {
    "id": "html-ppt-tech-sharing",
    "slug": "html-ppt-tech-sharing",
    "name": "html-ppt-tech-sharing"
  },
  {
    "id": "html-ppt-testing-safety-alert",
    "slug": "html-ppt-testing-safety-alert",
    "name": "html-ppt-testing-safety-alert"
  },
  {
    "id": "html-ppt-weekly-report",
    "slug": "html-ppt-weekly-report",
    "name": "html-ppt-weekly-report"
  },
  {
    "id": "html-ppt-xhs-pastel-card",
    "slug": "html-ppt-xhs-pastel-card",
    "name": "html-ppt-xhs-pastel-card"
  },
  {
    "id": "html-ppt-xhs-post",
    "slug": "html-ppt-xhs-post",
    "name": "html-ppt-xhs-post"
  },
  {
    "id": "html-ppt-xhs-white-editorial",
    "slug": "html-ppt-xhs-white-editorial",
    "name": "html-ppt-xhs-white-editorial"
  },
  {
    "id": "hyperframes",
    "slug": "hyperframes",
    "name": "hyperframes"
  },
  {
    "id": "image-poster",
    "slug": "image-poster",
    "name": "image-poster"
  },
  {
    "id": "invoice",
    "slug": "invoice",
    "name": "invoice"
  },
  {
    "id": "kami-deck",
    "slug": "kami-deck",
    "name": "kami-deck"
  },
  {
    "id": "kami-landing",
    "slug": "kami-landing",
    "name": "kami-landing"
  },
  {
    "id": "kanban-board",
    "slug": "kanban-board",
    "name": "kanban-board"
  },
  {
    "id": "live-artifact",
    "slug": "live-artifact",
    "name": "live-artifact"
  },
  {
    "id": "magazine-poster",
    "slug": "magazine-poster",
    "name": "magazine-poster"
  },
  {
    "id": "meeting-notes",
    "slug": "meeting-notes",
    "name": "meeting-notes"
  },
  {
    "id": "mobile-app",
    "slug": "mobile-app",
    "name": "mobile-app"
  },
  {
    "id": "mobile-onboarding",
    "slug": "mobile-onboarding",
    "name": "mobile-onboarding"
  },
  {
    "id": "motion-frames",
    "slug": "motion-frames",
    "name": "motion-frames"
  },
  {
    "id": "open-design-landing",
    "slug": "open-design-landing",
    "name": "open-design-landing"
  },
  {
    "id": "open-design-landing-deck",
    "slug": "open-design-landing-deck",
    "name": "open-design-landing-deck"
  },
  {
    "id": "orbit-general",
    "slug": "orbit-general",
    "name": "orbit-general"
  },
  {
    "id": "orbit-github",
    "slug": "orbit-github",
    "name": "orbit-github"
  },
  {
    "id": "orbit-gmail",
    "slug": "orbit-gmail",
    "name": "orbit-gmail"
  },
  {
    "id": "orbit-linear",
    "slug": "orbit-linear",
    "name": "orbit-linear"
  },
  {
    "id": "orbit-notion",
    "slug": "orbit-notion",
    "name": "orbit-notion"
  },
  {
    "id": "pm-spec",
    "slug": "pm-spec",
    "name": "pm-spec"
  },
  {
    "id": "pptx-html-fidelity-audit",
    "slug": "pptx-html-fidelity-audit",
    "name": "pptx-html-fidelity-audit"
  },
  {
    "id": "pricing-page",
    "slug": "pricing-page",
    "name": "pricing-page"
  },
  {
    "id": "replit-deck",
    "slug": "replit-deck",
    "name": "replit-deck"
  },
  {
    "id": "saas-landing",
    "slug": "saas-landing",
    "name": "saas-landing"
  },
  {
    "id": "simple-deck",
    "slug": "simple-deck",
    "name": "simple-deck"
  },
  {
    "id": "social-carousel",
    "slug": "social-carousel",
    "name": "social-carousel"
  },
  {
    "id": "social-media-dashboard",
    "slug": "social-media-dashboard",
    "name": "social-media-dashboard"
  },
  {
    "id": "sprite-animation",
    "slug": "sprite-animation",
    "name": "sprite-animation"
  },
  {
    "id": "team-okrs",
    "slug": "team-okrs",
    "name": "team-okrs"
  },
  {
    "id": "tweaks",
    "slug": "tweaks",
    "name": "tweaks"
  },
  {
    "id": "video-shortform",
    "slug": "video-shortform",
    "name": "video-shortform"
  },
  {
    "id": "waitlist-page",
    "slug": "waitlist-page",
    "name": "waitlist-page"
  },
  {
    "id": "web-prototype",
    "slug": "web-prototype",
    "name": "web-prototype"
  },
  {
    "id": "web-prototype-taste-brutalist",
    "slug": "web-prototype-taste-brutalist",
    "name": "web-prototype-taste-brutalist"
  },
  {
    "id": "web-prototype-taste-editorial",
    "slug": "web-prototype-taste-editorial",
    "name": "web-prototype-taste-editorial"
  },
  {
    "id": "web-prototype-taste-soft",
    "slug": "web-prototype-taste-soft",
    "name": "web-prototype-taste-soft"
  },
  {
    "id": "weekly-update",
    "slug": "weekly-update",
    "name": "weekly-update"
  },
  {
    "id": "wireframe-sketch",
    "slug": "wireframe-sketch",
    "name": "wireframe-sketch"
  }
];
